"""empty message

Revision ID: 1db3d3bb2c43
Revises: None
Create Date: 2016-04-21 18:03:30.291695

"""

# revision identifiers, used by Alembic.
revision = '1db3d3bb2c43'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norek', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pemasukan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('createdtime', sa.DateTime(), nullable=True),
    sa.Column('updatedtime', sa.DateTime(), nullable=True),
    sa.Column('deletedtime', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penarikan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('createdtime', sa.DateTime(), nullable=True),
    sa.Column('updatedtime', sa.DateTime(), nullable=True),
    sa.Column('deletedtime', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('tujuan', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('createdtime', sa.DateTime(), nullable=True),
    sa.Column('updatedtime', sa.DateTime(), nullable=True),
    sa.Column('deletedtime', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('penarikan')
    op.drop_table('pemasukan')
    op.drop_table('user')
    ### end Alembic commands ###
