"""empty message

Revision ID: d08cdadab572
Revises: 1db3d3bb2c43
Create Date: 2016-04-21 18:38:55.825048

"""

# revision identifiers, used by Alembic.
revision = 'd08cdadab572'
down_revision = '1db3d3bb2c43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=11), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###
